### ISSUE TITLE
can you share your style transfer model?

### ISSUE THREAD

**Issue by daxiangpanda** [fritzlabs/fritz-style-transfer#3]
can you share your style transfer model? thx

**Comment by jamesonthecrow** [comment]
11 pretrained models are available in the FritzVisionStylw SDK. You can try them out in our open source Heartbeat app for iOS:

https://github.com/fritzlabs/heartbeat-ios/tree/fritz-style-transfer-beta

Try it out and let us know how you find it!

**Comment by jamesonthecrow** [comment]
I've now added an example model in the `example/` folder.
