### ISSUE TITLE
About the dog image transfered to starry night

### ISSUE THREAD

**Issue by limchaos** [fritzlabs/fritz-style-transfer#6]
Nice work ,thanks for your share!
The dog image transfered to starry night seemed not use GRAM matrix or set a low style weight (I guess),It seemed not as good as Jonson's model. can I ask what is the different between this implementation and the original one.
best,
Ding

**Comment by jamesonthecrow** [comment]
Hi Ding,

This style transfer models uses the same GRAM matrix comparison from the Johnson et al paper. The style weight was set a little low for the starry night model. You can see models with a higher style weight in our Heartbeat demo application available on [iOS](bit.ly/heartbeat-ios) or [Android](bit.ly/heartbeat-android).

**Comment by limchaos** [comment]
Thanks
